# Generated by Django 4.1.1 on 2022-09-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("결제완료", "Payment completed"),
                            ("결제대기", "waiting for payment"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("신용카드", "Credit card"),
                            ("무통장입금", "Deposit without bankbook"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={"db_table": "payments",},
        ),
    ]
