# Generated by Django 4.1.1 on 2022-09-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
