# Generated by Django 4.1.1 on 2022-09-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="seller",),
    ]
